### ISSUE TITLE
MacOS Fails to build on boost@1.86

### ISSUE THREAD

**Issue by mali-tintash** [esbmc/esbmc#1993]
I started running into this issue today when building esbmc.

> `src/util/crypto_hash.cpp:47:26: error: non-const lvalue reference to type 'digest_type' (aka 'unsigned char[20]') cannot bind to a value of unrelated type 'unsigned int[5]'
>   p_crypto->s.get_digest(hash);

> /opt/homebrew/include/boost/uuid/detail/sha1.hpp:179:43: note: passing argument to parameter 'digest' here
> inline void sha1::get_digest(digest_type& digest)`

On investigating, it seems by boost version was upgraded from 1.85 to 1.86.
The change log has this particular line of code from 1.85 to 1.86
`typedef unsigned int(digest_type)[5]; => typedef unsigned char digest_type[ 20 ];`

reverting to boost 1.85 works.

**Comment by lucasccordeiro** [comment]
This PR https://github.com/esbmc/esbmc/pull/1997 should fix this issue.
