### PR TITLE
[c2goto] Bind the filesystem the FLAIL macros register into

### LINKED ISSUE #7112: [build] master does not compile: 'fs' undeclared in cprover_libc_sources.cpp
`master` at `2284cf241d` does not compile. Introduced by #6766, merged today.

```
$ cmake -GNinja -Bbuild -S . -DDOWNLOAD_DEPENDENCIES=On -DENABLE_PYTHON_FRONTEND=On \
    -DENABLE_Z3=On -DBUILD_TESTING=On -DENABLE_REGRESSION=On -DCMAKE_BUILD_TYPE=RelWithDebInfo
$ ninja -C build esbmc
FAILED: src/c2goto/CMakeFiles/c2goto.dir/cprover_libc_sources.cpp.o
src/c2goto/cprover_libc_sources.cpp:64:3: error: 'fs' was not declared in this scope; did you mean 'ffs'?
   64 |   fs.add_bundled(vfs_musl + "/" #__VA_ARGS__, body, size);
      |   ^~
```

`register_bundled_libc()` in `src/c2goto/cprover_libc_sources.cpp` uses `fs` in five `ESBMC_FLAIL` expansions:

```
64:  fs.add_bundled(vfs_musl + "/" #__VA_ARGS__, body, size);
69:  fs.add_bundled(vfs_musl + "/" #__VA_ARGS__, body, size);
74:  fs.add_bundled(vfs_cpp + "/" #__VA_ARGS__, body, size);
80:    fs.add_bundled(vfs_python + "/" #__VA_ARGS__, body, size);
88:    fs.add_bundled(vfs_solidity + "/" #__VA_ARGS__, body, size);
```

but nothing declares it. The two blocks above them spell the same call out in full:

```cpp
#define ESBMC_FLAIL(body, size, ...)                                           \
  file_operations::filesystemt::get().add_bundled(                             \
    vfs_headers + "/" #__VA_ARGS__, body, size);
```

`git show 2284cf241d -- src/c2goto/cprover_libc_sources.cpp` shows the five `fs.` lines added with no accompanying declaration, so the intent looks like a `auto &fs = file_operations::filesystemt::get();` binding at the top of the function that did not land.

Fix is a one-liner; opening a PR alongside this.

Environment: Ubuntu 22.04 under WSL2, g++-12, ninja. Nothing local involved -- the file is byte-identical to `origin/master` and the failure reproduces on a fresh `cmake` regeneration.

Worth checking why CI did not catch it, since every build job should have.

### PR DESCRIPTION
**Pull request by LukeW1999**
Fixes #7112. `master` at `2284cf241d` does not compile.

```
FAILED: src/c2goto/CMakeFiles/c2goto.dir/cprover_libc_sources.cpp.o
src/c2goto/cprover_libc_sources.cpp:64:3: error: 'fs' was not declared in this scope; did you mean 'ffs'?
   64 |   fs.add_bundled(vfs_musl + "/" #__VA_ARGS__, body, size);
```

`register_bundled_libc` uses `fs` in five `ESBMC_FLAIL` expansions and nothing declares it. #6766 added those five; the three blocks that predate it spell `file_operations::filesystemt::get().add_bundled(...)` out in full.

Bind it once at the top of the function and let every block use it, rather than leaving two spellings of the same call in one function.

## Checks

- builds clean
- `regression/function_contract` and `regression/python-contracts` 457/457
- runtime sanity, since compiling is not evidence the models are still mounted: a C file reaching `memset` and `fabs`, and a Python file reaching the list model, both verify

Worth a look at why CI did not catch this -- every build job should have.

### CODE REVIEW

**Comment by LukeW1999** [comment]
Duplicate of #7110, which makes the same change -- bind `fs` and unify every FLAIL block on it -- and was opened 49 minutes earlier by the author of #6766. #7111 is the minimal variant of the same fix. Closing this one; a third is no help.

My mistake in opening it: I searched open **issues** for an existing report and found none, but never searched open **PRs**, where two fixes were already waiting.
