### ISSUE TITLE
[build] master does not compile: 'fs' undeclared in cprover_libc_sources.cpp

### ISSUE THREAD

**Issue by LukeW1999** [esbmc/esbmc#7112]
`master` at `2284cf241d` does not compile. Introduced by #6766, merged today.

```
$ cmake -GNinja -Bbuild -S . -DDOWNLOAD_DEPENDENCIES=On -DENABLE_PYTHON_FRONTEND=On \
    -DENABLE_Z3=On -DBUILD_TESTING=On -DENABLE_REGRESSION=On -DCMAKE_BUILD_TYPE=RelWithDebInfo
$ ninja -C build esbmc
FAILED: src/c2goto/CMakeFiles/c2goto.dir/cprover_libc_sources.cpp.o
src/c2goto/cprover_libc_sources.cpp:64:3: error: 'fs' was not declared in this scope; did you mean 'ffs'?
   64 |   fs.add_bundled(vfs_musl + "/" #__VA_ARGS__, body, size);
      |   ^~
```

`register_bundled_libc()` in `src/c2goto/cprover_libc_sources.cpp` uses `fs` in five `ESBMC_FLAIL` expansions:

```
64:  fs.add_bundled(vfs_musl + "/" #__VA_ARGS__, body, size);
69:  fs.add_bundled(vfs_musl + "/" #__VA_ARGS__, body, size);
74:  fs.add_bundled(vfs_cpp + "/" #__VA_ARGS__, body, size);
80:    fs.add_bundled(vfs_python + "/" #__VA_ARGS__, body, size);
88:    fs.add_bundled(vfs_solidity + "/" #__VA_ARGS__, body, size);
```

but nothing declares it. The two blocks above them spell the same call out in full:

```cpp
#define ESBMC_FLAIL(body, size, ...)                                           \
  file_operations::filesystemt::get().add_bundled(                             \
    vfs_headers + "/" #__VA_ARGS__, body, size);
```

`git show 2284cf241d -- src/c2goto/cprover_libc_sources.cpp` shows the five `fs.` lines added with no accompanying declaration, so the intent looks like a `auto &fs = file_operations::filesystemt::get();` binding at the top of the function that did not land.

Fix is a one-liner; opening a PR alongside this.

Environment: Ubuntu 22.04 under WSL2, g++-12, ninja. Nothing local involved -- the file is byte-identical to `origin/master` and the failure reproduces on a fresh `cmake` regeneration.

Worth checking why CI did not catch it, since every build job should have.

**Comment by LukeW1999** [comment]
Already being fixed: #7110 (by the author of #6766) and #7111. I opened #7114 for the same thing before spotting them and have closed it.

**Why CI did not catch this**, which is the part worth keeping: the Actions queue is stalled, not failing. Of the last 60 workflow runs in this repo, 42 are `queued` and none completed successfully -- the rest are `skipped` or `cancelled`. The checks on #6766's head commit `83f86e670b` are all still `queued`, and so are the ones on the merge commit `2284cf241d` (started 09:29:12Z). So #6766 was merged with its CI never having run, rather than having run and passed.

That makes this less a gap in what CI checks than a case of the merge button being available while no runner had picked the job up. Anything merged today is in the same position.

**Comment by LukeW1999** [comment]
Fixed by #7123 (`59b3c32d82`, 2026-08-17), which restored the filesystem handle
the VFS flail blocks use. The commit is in `v8.5`.

Verified on master `da683e0dda`:

```
ninja -C build src/c2goto/CMakeFiles/c2goto.dir/cprover_libc_sources.cpp.o
```

builds clean, and `fs` no longer appears undeclared in that translation unit.
Closing.
